from array import*
jaanu=array('i',[1,2,3,4,5,6])
print(jaanu)
jaanu.append(19)
print(jaanu)
jaanu.reverse()
print(jaanu)
jaanu.remove(1)
print(jaanu)
print(jaanu.index(6))
jaanu.insert(6,55)
print(jaanu)
jaanu.pop(0)
print(jaanu)