print("hello")
print(8/4)
a=5/2
print(a)
b=2**3
print(b)
print(10//3)
print(10%3)
print("FUNCTIONS:PERFORM A SPECIFIC TASK\\")
print("it's self");print('its');
print("navin's","laptop")
print("mani's lover mounika")
x=2
print((x+10))
nums=[1,2,3,4,5,6,7,8]
print(nums)
print(nums[1])
print(nums[-1])
name='youtube'
print(name)
print(name[1])
print(name[2])
print(name[3])
print(name+" mani developer")
print(10*"\n mani loves jaanu")
print(nums[4])
print(nums[2:])
print(nums[:10])
names=["mani","muni","mounika"]
print(names[0])
print(names[2]+" loves mani")
print(names[1])
values=[9.5,'kiran',25]
print(type(values))
value=(9.5,'kiran',25)
print(type(value))
print(type(values[1]))
print(type(value[1]))
print(type(values[2]))
j=[1,2,3,4,5,6,7,8,9]
k=(1,2,3,34,4,5,4,5,25)
j.append(12)
print(j)
j.insert(2,555)
print(j)
j.remove(6);
print(j);
j.pop(4)
print(j);
j.sort()
print(j)
print(min(j))
print(max(j))
print(sum(j))
print(j)
data={1:"nabi",5:"muni",3:"mama"}
print(data)
print(data[1])
print(data[5])
print(data)
print(data.get(3))
print(data)
print(data.get(4,'not fouded'))
datas=['kiram','fahim','manchi']
data=dict(zip(data,datas))

print(datas[1])
print(data)
prog={'js':'atom','cs':'vs','java':'james gosling','python':['guido van roosum','pycharm'],'c':'denis rithche'}
print(prog)
print(prog['js'])
print(prog['python'])
print(prog['c'])
print(prog['java'])
print(prog['python'][1])
print(prog['python'][0])
merged=prog|data
print(dict(merged))
merged={**prog,**data}
print(merged)
prog.update(data)
print(prog)
m=555
print(id(m))
b=m
print(id(b))
n=m+10
print(n)
print(id(n))
print(n+0)
print(id(n))
o=2.5
print(type(o))
p=25
print(type(p))
q=2+6j
print(type(q))
o>p
print(type(o<p))
print(q+p)
print(type(q+p))
print(bool(o>p))
listt=[1,2,3,4,5,6,7]
print(type(listt))
print(sum(listt))
print(id(sum))
string='namess'
print(type(string))
even=list(range(0,100,2))
print(even)
odd=list(range(1,100,2))
print(odd)
print(prog.keys())
print(prog.values())